x-healthcheck-template: &healthcheck-template
  interval: 10s
  timeout: 5s
  retries: 3
  start_period: 10s

services:
  # Nginx reverse proxy
  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${PROXY_SERVICE_NAME}
    ports:
      - '8080:80'
      - '4430:443'
    networks:
      - app-network
    volumes:
      - ${HOST_VOLUME_PATH}:/usr/share/nginx/html/uploads:ro
    restart: unless-stopped
    depends_on:
      api-gateway:
        condition: service_started
    healthcheck:
      <<: *healthcheck-template
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'https://localhost/health']

  # Main Fastify API
  api-gateway:
    build:
      context: ..
      dockerfile: 'srcs/gateway/Dockerfile'
    container_name: '${API_GATEWAY_NAME}'
    expose:
      - '${API_GATEWAY_PORT}'
    env_file:
      - path: ./.env
      - path: ./.env.gateway
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      auth-service:
        condition: service_healthy

  # Auth service
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: '${AUTH_SERVICE_NAME}'
    expose:
      - '${AUTH_SERVICE_PORT}'
    env_file:
      - path: ./.env
      - path: ./.env.auth
    volumes:
      - data:/data
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      user-service:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck-template
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${AUTH_SERVICE_PORT}/health',
        ]

  # Blockchain service
  blockchain-service:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    container_name: '${BK_SERVICE_NAME}'
    expose:
      - '${BK_SERVICE_PORT}'
    env_file:
      - path: ./.env
      - path: ./.env.blockchain
    volumes:
      - data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck-template
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${BK_SERVICE_PORT}/health',
        ]

  game-service:
    build:
      context: ./game
      dockerfile: Dockerfile
    container_name: ${GAME_SERVICE_NAME}
    expose:
      - '${GAME_SERVICE_PORT}'
    env_file:
      - path: ./.env
      - path: ./.env.game
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck-template
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${GAME_SERVICE_PORT}/health',
        ]

  redis-broker:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: ${REDIS_SERVICE_NAME}
    expose:
      - '${REDIS_SERVICE_PORT}'
    networks:
      - app-network
    restart: unless-stopped

  user-service:
    build:
      context: ..
      dockerfile: srcs/users/Dockerfile
    container_name: ${UM_SERVICE_NAME}
    expose:
      - '${UM_SERVICE_PORT}'
    env_file:
      - path: ./.env
      - path: ./.env.um
    volumes:
      - data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      <<: *healthcheck-template
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:${UM_SERVICE_PORT}/health',
        ]

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
    driver_opts:
      device: ${HOST_VOLUME_PATH}
      o: bind
      type: none
